### ISSUE TITLE
The following assertion was thrown attaching to the render tree

### ISSUE THREAD

**Issue by alistarfire** [amangautam1/flutter-musicplayer#11]
I/flutter (28786): The following assertion was thrown attaching to the render tree:
I/flutter (28786): 'package:flutter/src/material/slider_theme.dart': Failed assertion: line 233 pos 16: 'trackHeight !=
I/flutter (28786): null': is not true.
I/flutter (28786): 
I/flutter (28786): Either the assertion indicates an error in the framework itself, or we should provide substantially

**Comment by denghuiquan** [comment]
i got the same error while running the code, too.

**Comment by amangautam1** [comment]
Fixed this in a new commit. check it now
