### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it.

### ISSUE THREAD

**Issue by imdarpn** [amangautam1/flutter-musicplayer#23]
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/digital/Darpan_AndroidWorks/flutter_project/flutter-musicplayer/android/app/src/nullnull/debug/google-services.json
  /home/digital/Darpan_AndroidWorks/flutter_project/flutter-musicplayer/android/app/src/debug/nullnull/google-services.json
  /home/digital/Darpan_AndroidWorks/flutter_project/flutter-musicplayer/android/app/src/nullnull/google-services.json
  /home/digital/Darpan_AndroidWorks/flutter_project/flutter-musicplayer/android/app/src/debug/google-services.json
  /home/digital/Darpan_AndroidWorks/flutter_project/flutter-musicplayer/android/app/src/nullnullDebug/google-services.json
  /home/digital/Darpan_AndroidWorks/flutter_project/flutter-musicplayer/android/app/google-services.json

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by casual-coder-25** [comment]
To build and check the app, comment out below lines
apply plugin: 'com.google.gms.google-services' in "..\flutter-musicplayer-master\android\app\build.gradle"

classpath 'com.google.gms:google-services:3.2.1' in "..\flutter-musicplayer-master\android\build.gradle"

firebase_admob: ^0.9.0+2 in "pubspec.yaml"
